# 기존 이미지 기반
FROM aveeslab/lane_detection:v5

# 작업 디렉터리 생성 및 설정
RUN mkdir -p /home/lane_detection
WORKDIR /home/lane_detection

# 필요한 애플리케이션 복사
COPY ./src /home/lane_detection/src

# ROS 빌드 의존성 설치
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    python3-colcon-common-extensions \
    x11-apps && \
    rm -rf /var/lib/apt/lists/*

# ROS 애플리케이션 빌드
RUN /bin/bash -c "source /opt/ros/foxy/setup.bash && colcon build"

# ROS 환경 설정 추가
RUN echo "source /opt/ros/foxy/setup.bash" >> /root/.bashrc && \
    echo "source /home/lane_detection/install/setup.bash" >> /root/.bashrc

# GUI를 위한 환경 변수 설정
ENV ROS_DOMAIN_ID=102
ENV DISPLAY=:0
VOLUME ["/tmp/.X11-unix"]

# 기본 실행 명령어
CMD ["/bin/bash", "-c", "source /opt/ros/foxy/setup.bash && source /home/lane_detection/install/setup.bash && bash"]


